// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.integration.samples.loanbroker.loanshark.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LoanShark_Roo_Configurable {
    
    declare @type: LoanShark: @Configurable;
    
}
